# Linear algebra in Python with NumPy


In this lab, you will have the opportunity to remember some basic concepts about linear algebra and how to use them in Python.

Numpy is one of the most used libraries in Python for arrays manipulation. It adds to Python a set of functions that allows us to operate on large multidimensional arrays with just a few lines. So forget about writing nested loops for adding matrices! With NumPy, this is as simple as adding numbers.

Let us import the `numpy` library and assign the alias `np` for it. We will follow this convention in almost every notebook in this course, and you'll see this in many resources outside this course as well.

In [1]:
import numpy as np


## Defining lists and numpy arrays

In [2]:
alist = [1,2,3,4,5]
narray = np.array(alist)

In [3]:
print(alist)
print(narray)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
print(type(alist))
print(type(narray))

<class 'list'>
<class 'numpy.ndarray'>


## Algebraic operators on NumPy arrays vs. Python lists

One of the common beginner mistakes is to mix up the concepts of NumPy arrays and Python lists. Just observe the next example, where we add two objects of the two mentioned types. Note that the '+' operator on NumPy arrays perform an element-wise addition, while the same operation on Python lists results in a list concatenation. Be careful while coding. Knowing this can save many headaches.

In [5]:
print(narray + narray)
print(alist + alist)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [6]:
print(narray * 3)


[ 3  6  9 12 15]


In [7]:
print(alist * 3)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## Matrix or Array of Arrays

In linear algebra, a matrix is a structure composed of n rows by m columns. That means each row must have the same number of columns. With NumPy, we have two ways to create a matrix:
* Creating an array of arrays using `np.array` (recommended). 
* Creating a matrix using `np.matrix` (still available but might be removed soon).

NumPy arrays or lists can be used to initialize a matrix, but the resulting matrix will be composed of NumPy arrays only.

In [8]:
npmatrix1 = np.array([narray, narray, narray])

In [9]:
print(npmatrix1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [11]:
npmatrix2 = np.array([alist, alist, alist])

In [13]:
print(npmatrix2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [16]:
npmatrix3 = np.array([narray, [3,4,2,3,4], narray])

In [18]:
print(npmatrix3)

[[1 2 3 4 5]
 [3 4 2 3 4]
 [1 2 3 4 5]]


However, when defining a matrix, be sure that all the rows contain the same number of elements. Otherwise, the linear algebra operations could lead to unexpected results.

Analyze the following two examples:

In [20]:
okmatrix = np.array([[1,2],[3,4]])

In [23]:
print(okmatrix)

[[1 2]
 [3 4]]


In [24]:
print(okmatrix * 2)

[[2 4]
 [6 8]]


In [26]:
badmatrix = np.array([[1,2],[3,4],[5,6,7]])
print(badmatrix)
print(badmatrix * 3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## Scaling and translating matrices

Now that you know how to build correct NumPy arrays and matrices, let us see how easy it is to operate with them in Python using the regular algebraic operators like + and -. 

Operations can be performed between arrays and arrays or between arrays and scalars.

In [27]:
# Scale by 2 and translate 1 unit the matrix
result = okmatrix * 2 + 1 # For each element in the matrix, multiply by 2 and add 1
print(result)

[[3 5]
 [7 9]]


In [28]:
result = okmatrix * okmatrix
print(result)

[[ 1  4]
 [ 9 16]]


## Transpose a matrix

In linear algebra, the transpose of a matrix is an operator that flips a matrix over its diagonal, i.e., the transpose operator switches the row and column indices of the matrix producing another matrix. If the original matrix dimension is n by m, the resulting transposed matrix will be m by n.

**T** denotes the transpose operations with NumPy matrices.

In [30]:
matrix3x2 = np.array([[3,4],[3,2],[4,3]])
print(matrix3x2)

[[3 4]
 [3 2]
 [4 3]]


In [31]:
print(matrix3x2.T)

[[3 3 4]
 [4 2 3]]


## Get the norm of a nparray or matrix

In linear algebra, the norm of an n-dimensional vector $\vec a$   is defined as:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2}$$

Calculating the norm of vector or even of a matrix is a general operation when dealing with data. Numpy has a set of functions for linear algebra in the subpackage **linalg**, including the **norm** function. Let us see how to get the norm a given array or matrix:

In [33]:
nparray1 = np.array([1,2,3,4])
norm1 = np.linalg.norm(nparray1)

In [36]:
print(norm1)

5.477225575051661


In [41]:
nparray2 = np.array([[3,2],[3,3]])
print(np.linalg.norm(nparray2))

5.5677643628300215


In [42]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2 - np.mean(nparray2, axis=0) # Remove the mean for each column

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]
